const express = require('express');

const router = express.Router();

const numeroCampionature = require('./numero_campionature');
const effCampionature = require('./eff_campionature');
const rapCampionature = require('./rap_campionature');
const costiNonQualita = require('./costi_nonqualita');
const addebiti = require('./addebiti');
const ppmScarti = require('./ppm_scarti');
const internalNc = require('./internal_nc');
const kpiExternal = require('./kpi_external');
const d8TempoChiusura = require('./8d_tempo_chiusura');
const d8Nuovi = require('./8d_nuovi');
const ncReparti = require('./nc_reparti');
const azioniMiglioramentoNew = require('./azioni_miglioramento_new');
const azioniMiglioramentoNew2 = require('./azioni_miglioramento_new2');
const azioniMiglioramentoTag = require('./azioni_miglioramento_tag');
const azioniMiglioramentoTag2 = require('./azioni_miglioramento_tag2');
const emissioni = require('./emissioni');
const emissioniMedia = require('./emissioni_media');
const consumoMateriePrime = require('./consumo_materie_prime');
const ncLogistica = require('./nc_logistica');
const ncManutentive = require('./nc_manutentive');
const costoNonQualitaLogistica = require('./costo_non_qualita_logistica');
const costoNonQualitaManutentive = require('./costo_non_qualita_manutentive');
const resaMediaTrasporti = require('./resa_media_trasporti');
const costoMedioTrasporti = require('./costo_medio_trasporti');
const percLeadTime = require('./perc_lead_time');
const ltMedio = require('./lt_medio');
const registroInduzionePonderato = require('./registro_induzione_ponderato');
const analisiPerditeInduzione = require('./analisi_perdite_induzione');
const analisiPerditeInduzionePie = require('./analisi_perdite_induzione_pie');
const produttivitaInduzione = require('./produttivita_induzione');
const saturazioneInduzione = require('./saturazione_induzione');
const registroInduzione = require('./registro_induzione');
const tassoQualita = require('./tasso_qualita');
const saturazioneCommerciale = require('./saturazione_commerciale');
const oee = require('./oee');
const efficienzaProduttiva = require('./efficienza_produttiva');
const resaCaricaMedia = require('./resa_carica_media');
const sintesiImpianti = require('./sintesi_impianti');
const reportProduzione = require('./report_produzione');
const reportAcquisti = require('./report_acquisti');
const reportCommerciale = require('./report_commerciale');
const reportInduzione = require('./report_induzione');
const reportPerformanceFornitori = require('./report_performance_fornitori');
const reportPerformanceClienti = require('./report_performance_clienti');
const reportPzhClienti = require('./report_pzh_clienti');
const reportCostiMateriePrime = require('./report_costi_materie_prime');
const reportCostiMateriePrimeMensile = require('./report_costi_materie_prime_mensile');

const rifiutiProdotti = require('./rifiuti_prodotti');
const energiaConsumata = require('./energia_consumata');
const energiaConsumataMetano = require('./energia_consumata_metano');
const equipmentAvailability = require('./equipment_availability');
const rapiditaManutenzione = require('./rapidita_manutenzione');
const meanTimeToRepair = require('./mean_time_to_repair');
const meanTimeBetweenRepair = require('./mean_time_between_repair');
const ripartizioneOreManutenzione = require('./ripartizione_ore_manutenzione');
const attivitaManutenzione = require('./attivita_manutenzione');
const indebitamentoPercentuale = require('./indebitamento_percentuale');
const rodConcorrenti = require('./rod_concorrenti');
const rosConcorrenti = require('./ros_concorrenti');
const attivo = require('./attivo');
const percCreditiInesigibili = require('./perc_crediti_inesigibili');
const percInsoluti = require('./perc_insoluti');
const costiConcorrenti = require('./costi_concorrenti');
const ebtda = require('./ebtda');
const roi = require('./roi');
const costoMateriePrimeCRM = require('./costo_materie_prime_crm');
const costoMateriePrimeTS = require('./costo_materie_prime_ts');
const rncFornitoriCRM = require('./rnc_fornitori_crm');
const rncFornitoriTS = require('./rnc_fornitori_ts');
const puntualitaFornitoriCRM = require('./puntualita_fornitori_crm');
const puntualitaFornitoriTS = require('./puntualita_fornitori_ts');
const puntualitaMateriePrimeTS = require('./puntualita_materieprime_ts');
const ritardoMedioFornitoriCRM = require('./ritardo_medio_fornitori_crm');
const ritardoMedioFornitoriTS = require('./ritardo_medio_fornitori_ts');
const leadTimeFornitoriTS = require('./lead_time_fornitori_ts');
const quoteDiMercato = require('./quote_di_mercato');
const quoteDiMercatoPie = require('./quote_di_mercato_pie');
const motiviRinunciaNumero = require('./motivi_rinuncia_numero');
const motiviRinunciaNumeroTs = require('./motivi_rinuncia_numero_ts');
const motiviRinunciaValore = require('./motivi_rinuncia_valore');
const motiviRinunciaValoreTs = require('./motivi_rinuncia_valore_ts');
const budgetFatturato = require('./budget_fatturato');
const fatturatoPerMese = require('./fatturato_per_mese');
const gdc80Perc = require('./gdc_80_perc');
const variazionePrezzi = require('./variazione_prezzi');
const tempoDiIncasso = require('./tempo_di_incasso');
const efficaciaCommerciale = require('./efficacia_commerciale');
const valoreOfferteNelTempo = require('./valore_offerte_nel_tempo');
const fatturatoConfronto = require('./fatturato_confronto');
const fatturatoMacroareeConfronto = require('./fatturato_macroaree_confronto');
const fatturatoCdlConfronto = require('./fatturato_cdl_confronto');
const fatturatoGruppiLavConfronto = require('./fatturato_gruppi_lavorazioni_confronto');
const fatturatoMacroaree = require('./fatturato_macroaree');
const fatturatoGruppiLavorazioni = require('./fatturato_gruppi_lavorazioni');
const fatturatoCdl = require('./fatturato_cdl');
const fatturatoClienti = require('./fatturato_clienti');
const percInvestimentoFormazione = require('./perc_investimento_formazione');
const percInfortuni = require('./perc_infortuni');
const percQuasiInfortuni = require('./perc_quasi_infortuni');
const motivazioneDipendenti = require('./motivazione_dipendenti');
const percAssenteismo = require('./perc_assenteismo');
const percFormazione = require('./perc_formazione');
const percStraordinario = require('./perc_straordinario');
const percFerieResidue = require('./perc_ferie_residue');
const laboratorio = require('./laboratorio');

module.exports = () => {
  router.use('/numero_campionature', numeroCampionature());
  router.use('/efficacia_campionature', effCampionature());
  router.use('/rapidita_campionature', rapCampionature());
  router.use('/costi_nonqualita', costiNonQualita());
  router.use('/addebiti', addebiti());
  router.use('/ppm_scarti', ppmScarti());
  router.use('/internal_nc', internalNc());
  router.use('/kpi_external', kpiExternal());
  router.use('/8d_tempo_chiusura', d8TempoChiusura());
  router.use('/8d_nuovi', d8Nuovi());
  router.use('/nc_reparti', ncReparti());
  router.use('/azioni_miglioramento_new', azioniMiglioramentoNew());
  router.use('/azioni_miglioramento_new2', azioniMiglioramentoNew2());
  router.use('/azioni_miglioramento_tags', azioniMiglioramentoTag());
  router.use('/azioni_miglioramento_tags2', azioniMiglioramentoTag2());
  router.use('/emissioni', emissioni());
  router.use('/emissioni_media', emissioniMedia());
  router.use('/consumo_materie_prime', consumoMateriePrime());
  router.use('/nc_logistica', ncLogistica());
  router.use('/costo_non_qualita_logistica', costoNonQualitaLogistica());
  router.use('/costo_non_qualita_manutentive', costoNonQualitaManutentive());
  router.use('/resa_media_trasporti', resaMediaTrasporti());
  router.use('/costo_medio_trasporti', costoMedioTrasporti());
  router.use('/perc_lead_time', percLeadTime());
  router.use('/lt_medio', ltMedio());
  router.use('/registro_induzione_ponderato', registroInduzionePonderato());
  router.use('/analisi_perdite_induzione', analisiPerditeInduzione());
  router.use('/analisi_perdite_induzione_pie', analisiPerditeInduzionePie());
  router.use('/produttivita_induzione', produttivitaInduzione());
  router.use('/saturazione_induzione', saturazioneInduzione());
  router.use('/registro_induzione', registroInduzione());
  router.use('/tasso_qualita', tassoQualita());
  router.use('/saturazione_commerciale', saturazioneCommerciale());
  router.use('/oee', oee());
  router.use('/efficienza_produttiva', efficienzaProduttiva());
  router.use('/resa_carica_media', resaCaricaMedia());
  router.use('/sintesi_impianti', sintesiImpianti());
  router.use('/report_produzione', reportProduzione());
  router.use('/report_acquisti', reportAcquisti());
  router.use('/report_commerciale', reportCommerciale());
  router.use('/report_induzione', reportInduzione());
  router.use('/report_performance_fornitori', reportPerformanceFornitori());
  router.use('/report_performance_clienti', reportPerformanceClienti());
  router.use('/report_pzh_clienti', reportPzhClienti());
  router.use('/report_costi_materie_prime', reportCostiMateriePrime());
  router.use('/report_costi_materie_prime_mensile', reportCostiMateriePrimeMensile());
  router.use('/rifiuti_prodotti', rifiutiProdotti());
  router.use('/energia_consumata', energiaConsumata());
  router.use('/energia_consumata_metano', energiaConsumataMetano());
  router.use('/equipment_availability', equipmentAvailability());
  router.use('/rapidita_manutenzione', rapiditaManutenzione());
  router.use('/mean_time_to_repair', meanTimeToRepair());
  router.use('/mean_time_between_repair', meanTimeBetweenRepair());
  router.use('/ripartizione_ore_manutenzione', ripartizioneOreManutenzione());
  router.use('/nc_manutentive', ncManutentive());
  router.use('/attivita_manutenzione', attivitaManutenzione());
  router.use('/indebitamento_percentuale', indebitamentoPercentuale());
  router.use('/rod_concorrenti', rodConcorrenti());
  router.use('/ros_concorrenti', rosConcorrenti());
  router.use('/attivo', attivo());
  router.use('/perc_crediti_inesigibili', percCreditiInesigibili());
  router.use('/perc_insoluti', percInsoluti());
  router.use('/costi_concorrenti', costiConcorrenti());
  router.use('/ebtda', ebtda());
  router.use('/roi', roi());
  router.use('/costo_materie_prime_crm', costoMateriePrimeCRM());
  router.use('/costo_materie_prime_ts', costoMateriePrimeTS());
  router.use('/rnc_fornitori_crm', rncFornitoriCRM());
  router.use('/rnc_fornitori_ts', rncFornitoriTS());
  router.use('/puntualita_fornitori_crm', puntualitaFornitoriCRM());
  router.use('/puntualita_fornitori_ts', puntualitaFornitoriTS());
  router.use('/puntualita_materieprime_ts', puntualitaMateriePrimeTS());
  router.use('/ritardo_medio_fornitori_crm', ritardoMedioFornitoriCRM());
  router.use('/ritardo_medio_fornitori_ts', ritardoMedioFornitoriTS());
  router.use('/lead_time_fornitori_ts', leadTimeFornitoriTS());
  router.use('/quote_di_mercato', quoteDiMercato());
  router.use('/quote_di_mercato_pie', quoteDiMercatoPie());
  router.use('/motivi_rinuncia_numero', motiviRinunciaNumero());
  router.use('/motivi_rinuncia_numero_ts', motiviRinunciaNumeroTs());
  router.use('/motivi_rinuncia_valore', motiviRinunciaValore());
  router.use('/motivi_rinuncia_valore_ts', motiviRinunciaValoreTs());
  router.use('/budget_fatturato', budgetFatturato());
  router.use('/fatturato_per_mese', fatturatoPerMese());
  router.use('/gdc_80_perc', gdc80Perc());
  router.use('/variazione_prezzi', variazionePrezzi());
  router.use('/tempo_di_incasso', tempoDiIncasso());
  router.use('/efficacia_commerciale', efficaciaCommerciale());
  router.use('/valore_offerte_nel_tempo', valoreOfferteNelTempo());
  router.use('/fatturato_confronto', fatturatoConfronto());
  router.use('/fatturato_macroaree', fatturatoMacroaree());
  router.use('/fatturato_cdl', fatturatoCdl());
  router.use('/fatturato_gruppi_lavorazioni', fatturatoGruppiLavorazioni());
  router.use('/fatturato_macroaree_confronto', fatturatoMacroareeConfronto());
  router.use('/fatturato_cdl_confronto', fatturatoCdlConfronto());
  router.use('/fatturato_gruppi_lavorazioni_confronto', fatturatoGruppiLavConfronto());
  router.use('/fatturato_clienti', fatturatoClienti());
  router.use('/perc_investimento_formazione', percInvestimentoFormazione());
  router.use('/perc_infortuni', percInfortuni());
  router.use('/perc_quasi_infortuni', percQuasiInfortuni());
  router.use('/motivazione_dipendenti', motivazioneDipendenti());
  router.use('/perc_assenteismo', percAssenteismo());
  router.use('/perc_formazione', percFormazione());
  router.use('/perc_straordinario', percStraordinario());
  router.use('/perc_ferie_residue', percFerieResidue());
  router.use('/laboratorio', laboratorio());
  return router;
};
