import { Type } from '@angular/core';
import { D8NuoviComponent } from '../kpi/8d-nuovi/8d-nuovi.component';
import { D8TempoChiusuraComponent } from '../kpi/8d-tempo-chiusura/8d-tempo-chiusura.component';
import { AddebitiComponent } from '../kpi/addebiti/addebiti.component';
import { AnalisiPerditeInduzionePieComponent } from '../kpi/analisi-perdite-induzione-pie/analisi-perdite-induzione-pie.component';
import { AnalisiPerditeInduzioneComponent } from '../kpi/analisi-perdite-induzione/analisi-perdite-induzione.component';
import { AzioniMiglioramentoNewComponent } from '../kpi/azioni-miglioramento-new/azioni-miglioramento-new.component';
import { AzioniMiglioramentoNew2Component } from '../kpi/azioni-miglioramento-new2/azioni-miglioramento-new2.component';
import { NumeroCampionatureComponent } from '../kpi/numero-campionature/numero-campionature.component';
import { CostiNonQualitaComponent } from '../kpi/costi-non-qualita/costi-non-qualita.component';
import { ConsumoMateriePrimeComponent } from '../kpi/consumo-materie-prime/consumo-materie-prime.component';
import { CostoMedioTrasportiComponent } from '../kpi/costo-medio-trasporti/costo-medio-trasporti.component';
import { CostoNonQualitaLogisticaComponent } from '../kpi/costo-non-qualita-logistica/costo-non-qualita-logistica.component';
import { EfficaciaCampionatureComponent } from '../kpi/efficacia-campionature/efficacia-campionature.component';
import { EfficienzaProduttivaComponent } from '../kpi/efficienza-produttiva/efficienza-produttiva.component';
import { EmissioniComponent } from '../kpi/emissioni/emissioni.component';
import { EnergiaConsumataComponent } from '../kpi/energia-consumata/energia-consumata.component';
import { EnergiaConsumataMetanoComponent } from '../kpi/energia-consumata-metano/energia-consumata-metano.component';
import { NcManutentiveComponent } from '../kpi/nc-manutentive/nc-manutentive.component';
import { EquipmentAvailabilityComponent } from '../kpi/equipment-availability/equipment-availability.component';
import { InternalNCComponent } from '../kpi/internal-nc/internal-nc.component';
import { KPIExternalComponent } from '../kpi/kpi-external/kpi-external.component';
import { LTMedioComponent } from '../kpi/lt-medio/lt-medio.component';
import { MeanTimeBetweenRepairALUComponent } from '../kpi/mean-time-between-repair-ALU/mean-time-between-repair-ALU.component';
import { MeanTimeBetweenRepairLLFComponent } from '../kpi/mean-time-between-repair-LLF/mean-time-between-repair-LLF.component';
import { MeanTimeBetweenRepairNCVCieffeComponent } from '../kpi/mean-time-between-repair-NCVCieffe/mean-time-between-repair-NCVCieffe.component';
import { MeanTimeBetweenRepairNCVIpsenComponent } from '../kpi/mean-time-between-repair-NCVIpsen/mean-time-between-repair-NCVIpsen.component';
import { MeanTimeBetweenRepairINDComponent } from '../kpi/mean-time-between-repair-IND/mean-time-between-repair-IND.component';
import { MeanTimeBetweenRepairTVComponent } from '../kpi/mean-time-between-repair-TV/mean-time-between-repair-TV.component';
import { MeanTimeBetweenRepairComponent } from '../kpi/mean-time-between-repair/mean-time-between-repair.component';
import { MeanTimeToRepairALUComponent } from '../kpi/mean-time-to-repair-ALU/mean-time-to-repair-ALU.component';
import { MeanTimeToRepairLLFComponent } from '../kpi/mean-time-to-repair-LLF/mean-time-to-repair-LLF.component';
import { MeanTimeToRepairNCVCieffeComponent } from '../kpi/mean-time-to-repair-NCVCieffe/mean-time-to-repair-NCVCieffe.component';
import { MeanTimeToRepairNCVIpsenComponent } from '../kpi/mean-time-to-repair-NCVIpsen/mean-time-to-repair-NCVIpsen.component';
import { MeanTimeToRepairINDComponent } from '../kpi/mean-time-to-repair-IND/mean-time-to-repair-IND.component';
import { MeanTimeToRepairTVComponent } from '../kpi/mean-time-to-repair-TV/mean-time-to-repair-TV.component';
import { MeanTimeToRepairRepartiComponent } from '../kpi/mean-time-to-repair-reparti/mean-time-to-repair-reparti.component';
import { NCLogisticaComponent } from '../kpi/nc-logistica/nc-logistica.component';
import { NCRepartiComponent } from '../kpi/nc-reparti/nc-reparti.component';
import { OEEComponent } from '../kpi/oee/oee.component';
import { PercLeadTimeComponent } from '../kpi/perc-lead-time/perc-lead-time.component';
import { PPMScartiComponent } from '../kpi/ppm-scarti/ppm-scarti.component';
import { ProduttivitaInduzioneComponent } from '../kpi/produttivita-induzione/produttivita-induzione.component';
import { RapiditaCampionatureComponent } from '../kpi/rapidita-campionature/rapidita-campionature.component';
import { RapiditaManutenzioneComponent } from '../kpi/rapidita-manutenzione/rapidita-manutenzione.component';
import { RegistroInduzionePonderatoComponent } from '../kpi/registro-induzione-ponderato/registro-induzione-ponderato.component';
import { RegistroInduzioneComponent } from '../kpi/registro-induzione/registro-induzione.component';
import { ReportProduzioneComponent } from '../kpi/report-produzione/report-produzione.component';
import { ResaCaricaMediaComponent } from '../kpi/resa-carica-media/resa-carica-media.component';
import { ResaMediaTrasportiComponent } from '../kpi/resa-media-trasporti/resa-media-trasporti.component';
import { RifiutiProdottiComponent } from '../kpi/rifiuti-prodotti/rifiuti-prodotti.component';
import { RifiutiComponent } from '../kpi/rifiuti/rifiuti.component';
import { RipartizioneOreManutenzioneComponent } from '../kpi/ripartizione-ore-manutenzione/ripartizione-ore-manutenzione.component';
import { SaturazioneCommercialeComponent } from '../kpi/saturazione-commerciale/saturazione-commerciale.component';
import { SaturazioneInduzioneComponent } from '../kpi/saturazione-induzione/saturazione-induzione.component';
import { SintesiImpiantiComponent } from '../kpi/sintesi-impianti/sintesi-impianti.component';
import { TassoQualitaComponent } from '../kpi/tasso-qualita/tasso-qualita.component';
import { CostoNcManutentiveComponent } from '../kpi/costo-nc-manutentive/costo-nc-manutentive.component';
import { InterventiRichiestiDaProduzioneComponent } from '../kpi/interventi-richiesti-da-produzione/interventi-richiesti-da-produzione.component';
import { IndebitamentoPercentualeComponent } from '../kpi/indebitamento-percentuale/indebitamento-percentuale.component';
import { RodConcorrentiComponent } from '../kpi/rod-concorrenti/rod-concorrenti.component';
import { RosConcorrentiComponent } from '../kpi/ros-concorrenti/ros-concorrenti.component';
import { AttivoComponent } from '../kpi/attivo/attivo.component';
import { PercCreditiInesigibiliComponent } from '../kpi/perc-crediti-inesigibili/perc-crediti-inesigibili.component';
import { CostiConcorrentiComponent } from '../kpi/costi-concorrenti/costi-concorrenti.component';
import { EBTDAComponent } from '../kpi/ebtda/ebtda.component';
import { ROIComponent } from '../kpi/roi/roi.component';
import { PercInsolutiComponent } from '../kpi/perc-insoluti/perc-insoluti.component';
import { NCAmbienteComponent } from '../kpi/nc-ambiente/nc-ambiente.component';
import { NCSicurezzaComponent } from '../kpi/nc-sicurezza/nc-sicurezza.component';
import { NCQualitaComponent } from '../kpi/nc-qualita/nc-qualita.component';
import { CostoMateriePrimeCRMComponent } from '../kpi/costo-materie-prime-crm/costo-materie-prime-crm.component';
import { QuoteDiMercatoComponent } from '../kpi/quote-di-mercato/quote-di-mercato.component';
import { BudgetFatturatoComponent } from '../kpi/budget-fatturato/budget-fatturato.component';
import { FatturatoPerMeseComponent } from '../kpi/fatturato-per-mese/fatturato-per-mese.component';
import { RNCFornitoriCRMComponent } from '../kpi/rnc-fornitori-crm/rnc-fornitori-crm.component';
import { ReportAcquistiComponent } from '../kpi/report-acquisti/report-acquisti.component';
import { RNCFornitoriTSComponent } from '../kpi/rnc-fornitori-ts/rnc-fornitori-ts.component';
import { PuntualitaFornitoriCRMComponent } from '../kpi/puntualita-fornitori-crm/puntualita-fornitori-crm.component';
import { PuntualitaFornitoriTSComponent } from '../kpi/puntualita-fornitori-ts/puntualita-fornitori-ts.component';
import { RitardoMedioFornitoriCRMComponent } from '../kpi/ritardo-medio-fornitori-crm/ritardo-medio-fornitori-crm.component';
import { RitardoMedioFornitoriTSComponent } from '../kpi/ritardo-medio-fornitori-ts/ritardo-medio-fornitori-ts.component';
import { CostoMateriePrimeTSComponent } from '../kpi/costo-materie-prime-ts/costo-materie-prime-ts.component';
import { GDC80PercComponent } from '../kpi/gdc-80-perc/gdc-80-perc.component';
import { VariazionePrezziComponent } from '../kpi/variazione-prezzi/variazione-prezzi.component';
import { TempoDiIncassoComponent } from '../kpi/tempo-di-incasso/tempo-di-incasso.component';
import { QuoteDiMercatoPieComponent } from '../kpi/quote-di-mercato-pie/quote-di-mercato-pie.component';
import { MotiviRinunciaNumeroComponent } from '../kpi/motivi-rinuncia-numero/motivi-rinuncia-numero.component';
import { MotiviRinunciaNumeroTSComponent } from '../kpi/motivi-rinuncia-numero-ts/motivi-rinuncia-numero-ts.component';
import { MotiviRinunciaValoreTSComponent } from '../kpi/motivi-rinuncia-valore-ts/motivi-rinuncia-valore-ts.component';
import { MotiviRinunciaValoreComponent } from '../kpi/motivi-rinuncia-valore/motivi-rinuncia-valore.component';
import { EfficaciaCommercialeEmissioneComponent } from '../kpi/efficacia-commerciale-emissione/efficacia-commerciale-emissione.component';
import { EfficaciaCommercialeChiusuraComponent } from '../kpi/efficacia-commerciale-chiusura/efficacia-commerciale-chiusura.component';
import { ValoreOfferteNelTempoComponent } from '../kpi/valore-offerte-nel-tempo/valore-offerte-nel-tempo.component';
import { FatturatoConfrontoComponent } from '../kpi/fatturato-confronto/fatturato-confronto.component';
import { FatturatoMacroareeComponent } from '../kpi/fatturato-macroaree/fatturato-macroaree.component';
import { FatturatoCdlComponent } from '../kpi/fatturato-cdl/fatturato-cdl.component';
import { FatturatoGruppiLavorazioniComponent } from '../kpi/fatturato-gruppi-lavorazioni/fatturato-gruppi-lavorazioni.component';
import { FatturatoMacroareeConfrontoComponent } from '../kpi/fatturato-macroaree-confronto/fatturato-macroaree-confronto.component';
import { FatturatoClientiComponent } from '../kpi/fatturato-clienti/fatturato-clienti.component';
import { PercAssenteismoComponent } from '../kpi/perc-assenteismo/perc-assenteismo.component';
import { PercInvestimentoFormazioneComponent } from '../kpi/perc-investimento-formazione/perc-investimento-formazione.component';
import { PercInfortuniComponent } from '../kpi/perc-infortuni/perc-infortuni.component';
import { PercQuasiInfortuniComponent } from '../kpi/perc-quasi-infortuni/perc-quasi-infortuni.component';
import { MotivazioneDipendentiComponent } from '../kpi/motivazione-dipendenti/motivazione-dipendenti.component';
import { PuntualitaMateriePrimeTSComponent } from '../kpi/puntualita-materieprime-ts/puntualita-materieprime-ts.component';
import { LeadTimeFornitoriTSComponent } from '../kpi/lead-time-fornitori-ts/lead-time-fornitori-ts.component';
import { FatturatoGruppiLavorazioniConfrontoComponent } from '../kpi/fatturato-gruppi-lavorazioni-confronto/fatturato-gruppi-lavorazioni-confronto.component';
import { FatturatoCdlConfrontoComponent } from '../kpi/fatturato-cdl-confronto/fatturato-cdl-confronto.component';
import { PercFerieResidueComponent } from '../kpi/perc-ferie-residue/perc-ferie-residue.component';
import { PercStraordinarioComponent } from '../kpi/perc-straordinario/perc-straordinario.component';
import { CostiConcorrentiStackComponent } from '../kpi/costi-concorrenti-stack/costi-concorrenti-stack.component';
import { ReportCommercialeComponent } from '../kpi/report-commerciale/report-commerciale.component';
import { ReportInduzioneComponent } from '../kpi/report-induzione/report-induzione.component';
import { AzioniMiglioramentoTagsComponent } from '../kpi/azioni-miglioramento-tags/azioni-miglioramento-tags.component';
import { AzioniMiglioramentoTags2Component } from '../kpi/azioni-miglioramento-tags2/azioni-miglioramento-tags2.component';
import { OEEIndComponent } from '../kpi/oee-ind/oee-ind.component';
import { PercFormazioneComponent } from '../kpi/perc-formazione/perc-formazione.component';
import { EmissioniMediaComponent } from '../kpi/emissioni-media/emissioni-media.component';
import { LaboratorioKpiComponent } from '../kpi/laboratorio/laboratorio-kpi.component';
import { EquipmentAvailabilityRepartoComponent } from '../kpi/equipment-availability-reparto/equipment-availability-reparto.component';
import { MeanTimeToRepairComponent } from '../kpi/mean-time-to-repair/mean-time-to-repair.component';
import { MeanTimeBetweenRepairRepartiComponent } from '../kpi/mean-time-between-repair-reparti/mean-time-between-repair-reparti.component';
import { TassoQualitaRepartiComponent } from '../kpi/tasso-qualita-reparti/tasso-qualita-reparti.component';
import { EfficienzaProduttivaRepartiComponent } from '../kpi/efficienza-produttiva-reparti/efficienza-produttiva-reparti.component';
import { SaturazioneCommercialeRepartiComponent } from '../kpi/saturazione-commerciale-reparti/saturazione-commerciale-reparti.component';
import { OEERepartiComponent } from '../kpi/oee-reparti/oee-reparti.component';

export class WidgetConstants {
  private static widgets = new Map<number, Type<any>>();

  static build(): WidgetConstants {
    this.widgets.set(68, QuoteDiMercatoComponent);
    this.widgets.set(69, QuoteDiMercatoPieComponent);
    this.widgets.set(70, RosConcorrentiComponent);
    this.widgets.set(71, RodConcorrentiComponent);
    this.widgets.set(72, FatturatoPerMeseComponent);
    this.widgets.set(73, BudgetFatturatoComponent);
    this.widgets.set(74, FatturatoConfrontoComponent);
    this.widgets.set(75, FatturatoClientiComponent);
    this.widgets.set(78, FatturatoMacroareeComponent);
    this.widgets.set(79, FatturatoMacroareeConfrontoComponent);
    this.widgets.set(81, GDC80PercComponent);
    this.widgets.set(82, EfficaciaCommercialeEmissioneComponent);
    this.widgets.set(83, ValoreOfferteNelTempoComponent);
    this.widgets.set(84, TempoDiIncassoComponent);
    this.widgets.set(85, MotiviRinunciaNumeroComponent);
    this.widgets.set(86, VariazionePrezziComponent);
    this.widgets.set(88, RNCFornitoriCRMComponent);
    this.widgets.set(89, RitardoMedioFornitoriCRMComponent);
    this.widgets.set(90, PuntualitaFornitoriCRMComponent);
    this.widgets.set(91, CostoMateriePrimeCRMComponent);
    this.widgets.set(93, ReportAcquistiComponent);
    this.widgets.set(94, KPIExternalComponent);
    this.widgets.set(95, PPMScartiComponent);
    this.widgets.set(96, InternalNCComponent);
    this.widgets.set(97, AddebitiComponent);
    this.widgets.set(98, CostiNonQualitaComponent);
    this.widgets.set(100, PercInvestimentoFormazioneComponent);
    this.widgets.set(101, IndebitamentoPercentualeComponent);
    this.widgets.set(102, PercInsolutiComponent);
    this.widgets.set(103, EBTDAComponent);
    this.widgets.set(104, ROIComponent);
    this.widgets.set(105, AttivoComponent);
    this.widgets.set(106, PercCreditiInesigibiliComponent);
    this.widgets.set(107, EfficaciaCampionatureComponent);
    this.widgets.set(108, RapiditaCampionatureComponent);
    this.widgets.set(109, PercAssenteismoComponent);
    this.widgets.set(110, PercStraordinarioComponent);
    this.widgets.set(111, PercFerieResidueComponent);
    this.widgets.set(112, PercInfortuniComponent);
    this.widgets.set(113, MotivazioneDipendentiComponent);
    this.widgets.set(114, EfficienzaProduttivaComponent);
    this.widgets.set(115, TassoQualitaComponent);
    this.widgets.set(116, EquipmentAvailabilityRepartoComponent);
    this.widgets.set(117, SaturazioneCommercialeComponent);
    this.widgets.set(118, RapiditaManutenzioneComponent);
    this.widgets.set(120, RipartizioneOreManutenzioneComponent);
    this.widgets.set(121, LTMedioComponent);
    this.widgets.set(122, ReportProduzioneComponent);
    this.widgets.set(123, PercLeadTimeComponent);
    this.widgets.set(124, ResaCaricaMediaComponent);
    this.widgets.set(125, AnalisiPerditeInduzioneComponent);
    this.widgets.set(166, AnalisiPerditeInduzionePieComponent);
    this.widgets.set(126, ProduttivitaInduzioneComponent);
    this.widgets.set(127, SaturazioneInduzioneComponent);
    this.widgets.set(128, CostoNonQualitaLogisticaComponent);
    this.widgets.set(130, NCRepartiComponent);
    this.widgets.set(131, RegistroInduzioneComponent);
    this.widgets.set(132, RegistroInduzionePonderatoComponent);
    this.widgets.set(135, NCLogisticaComponent);
    this.widgets.set(136, MotiviRinunciaValoreComponent);
    this.widgets.set(137, OEEComponent);
    this.widgets.set(140, SintesiImpiantiComponent);
    this.widgets.set(143, NumeroCampionatureComponent);
    this.widgets.set(147, AzioniMiglioramentoNewComponent);
    this.widgets.set(149, InterventiRichiestiDaProduzioneComponent);
    this.widgets.set(150, AzioniMiglioramentoNew2Component);
    this.widgets.set(151, D8TempoChiusuraComponent);
    this.widgets.set(152, D8NuoviComponent);
    this.widgets.set(153, ResaMediaTrasportiComponent);
    this.widgets.set(154, CostoMedioTrasportiComponent);
    this.widgets.set(155, CostiConcorrentiComponent);
    this.widgets.set(157, MeanTimeToRepairRepartiComponent);
    this.widgets.set(158, MeanTimeBetweenRepairRepartiComponent);
    this.widgets.set(161, RifiutiComponent);
    this.widgets.set(162, EmissioniComponent);
    this.widgets.set(163, ConsumoMateriePrimeComponent);
    this.widgets.set(164, RifiutiProdottiComponent);
    this.widgets.set(165, EnergiaConsumataComponent);
    this.widgets.set(167, MeanTimeBetweenRepairLLFComponent);
    this.widgets.set(169, MeanTimeBetweenRepairNCVCieffeComponent);
    this.widgets.set(170, MeanTimeBetweenRepairNCVIpsenComponent);
    this.widgets.set(172, MeanTimeBetweenRepairTVComponent);
    this.widgets.set(173, MeanTimeBetweenRepairALUComponent);
    this.widgets.set(174, MeanTimeBetweenRepairINDComponent);
    this.widgets.set(175, MeanTimeToRepairLLFComponent);
    this.widgets.set(177, MeanTimeToRepairNCVCieffeComponent);
    this.widgets.set(178, MeanTimeToRepairNCVIpsenComponent);
    this.widgets.set(180, MeanTimeToRepairTVComponent);
    this.widgets.set(181, MeanTimeToRepairALUComponent);
    this.widgets.set(182, MeanTimeToRepairINDComponent);
    this.widgets.set(183, NcManutentiveComponent);
    this.widgets.set(184, CostoNcManutentiveComponent);
    this.widgets.set(185, NCAmbienteComponent);
    this.widgets.set(186, NCSicurezzaComponent);
    this.widgets.set(187, NCQualitaComponent);
    this.widgets.set(188, RNCFornitoriTSComponent);
    this.widgets.set(189, PuntualitaFornitoriTSComponent);
    this.widgets.set(190, RitardoMedioFornitoriTSComponent);
    this.widgets.set(191, CostoMateriePrimeTSComponent);
    this.widgets.set(192, MotiviRinunciaNumeroTSComponent);
    this.widgets.set(193, MotiviRinunciaValoreTSComponent);
    this.widgets.set(194, EfficaciaCommercialeChiusuraComponent);
    this.widgets.set(195, FatturatoCdlComponent);
    this.widgets.set(196, FatturatoGruppiLavorazioniComponent);
    this.widgets.set(197, PercQuasiInfortuniComponent);
    this.widgets.set(198, PuntualitaMateriePrimeTSComponent);
    this.widgets.set(199, LeadTimeFornitoriTSComponent);
    this.widgets.set(200, FatturatoCdlConfrontoComponent);
    this.widgets.set(201, FatturatoGruppiLavorazioniConfrontoComponent);
    this.widgets.set(202, CostiConcorrentiStackComponent);
    this.widgets.set(204, ReportCommercialeComponent);
    this.widgets.set(205, ReportInduzioneComponent);
    this.widgets.set(206, AzioniMiglioramentoTagsComponent);
    this.widgets.set(207, AzioniMiglioramentoTags2Component);
    this.widgets.set(208, OEEIndComponent);
    this.widgets.set(209, PercFormazioneComponent);
    this.widgets.set(210, EmissioniMediaComponent);
    this.widgets.set(211, LaboratorioKpiComponent);
    this.widgets.set(212, EquipmentAvailabilityComponent);
    this.widgets.set(213, MeanTimeBetweenRepairComponent);
    this.widgets.set(214, MeanTimeToRepairComponent);
    this.widgets.set(215, TassoQualitaRepartiComponent);
    this.widgets.set(216, EfficienzaProduttivaRepartiComponent);
    this.widgets.set(217, SaturazioneCommercialeRepartiComponent);
    this.widgets.set(218, OEERepartiComponent);
    this.widgets.set(219, EnergiaConsumataMetanoComponent);
    return new this();
  }

  static getWidgetNameFromId(id: number): Type<any> {
    if (this.widgets.size == 0) {
      this.build();
    }

    return this.widgets.get(id)!;
  }
}
