version: '3.8'

services:
  sapere_temprasud:
    image: 'mariadb:10.3.31'
    restart: 'always'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'sapere_temprasud'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    command: --init-file /data/application/init.sql
    volumes:
      - ./sapere_temprasud.sql:/data/application/init.sql
  temprasud_bi:
    image: 'mariadb:10.3.31'
    restart: 'always'
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'temprasud_bi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    command: --init-file /data/application/init.sql
    volumes:
      - ./temprasud_bi.sql:/data/application/init.sql
  fake-smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
