const express = require('express');

const router = express.Router();

const usersRoute = require('./users');
const rolesRoute = require('./roles');
const dashboardsRoute = require('./dashboards');
const kpiRoute = require('./kpi');
const kpiInfoRoute = require('./kpi_info');
const filtersRoute = require('./filters');
const assessmentRoute = require('./assessment');
const targetRoute = require('./target');
const emissioniRoute = require('./emissioni');
const limitiInquinanti = require('./limiti_inquinanti');
const rifiutiRoute = require('./rifiuti');
const materiePrimeRoute = require('./materie_prime');
const contatoriRoute = require('./contatori');
const contatoriMetanoRoute = require('./contatori_metano');
const puntiDiEmissioneRoute = require('./punti_di_emissione');
const inquinantiRoute = require('./inquinanti');
const tabellaImpianti = require('./tabella_gestione_impianti');
const tabellaImpiantiInd = require('./tabella_gestione_impianti_ind');
const tabellaImpiantiFvf = require('./tabella_gestione_impianti_fvf');
const tabellaRifiuti = require('./tabella_rifiuti_prodotti');
const tabellaContatoriMisurazioni = require('./tabella_contatori_misurazioni');
const tabellaContatoriMisurazioniMetano = require('./tabella_contatori_misurazioni_metano');
const tabellaManutenzione = require('./tabella_manutenzione');
const tabellaRitManutenzione = require('./tabella_rit_manutenzione');
const tabellaPersonale = require('./tabella_personale');
const tabellaCartellino = require('./tabella_cartellino');
const tabellaDirezione = require('./tabella_direzione');
const tabellaConcorrenti = require('./tabella_concorrenti');
const tabellaBudget = require('./tabella_budget');
const tabellaDatiCommerciali = require('./tabella_dati_commerciali');
const tabellaLaboratorio = require('./tabella_laboratorio');
const tabellaRiepilogoClienti = require('./riepilogo_clienti');
const tabellaOreFormazione = require('./tabella_ore_formazione');
const populate = require('./populate');
const createWidget = require('./create_widget');
const assignDashboard = require('./assign_dashboard');
const tabellaCostoMateriePrime = require('./tabella_costo_materieprime');
const tabellaFatturatoClienti = require('./tabella_fatturato_clienti');
const tabellaAumentoMpFornitori = require('./tabella_aumento_mp_fornitori');
const tabellaCostoFornitori = require('./tabella_costo_fornitori');
const tabellaMappingMp = require('./tabella_mapping_materie_prime');
const tabellaTeamsystemOrdini = require('./tabella_teamsystem_ordini');
const tabellaZohoTasks = require('./tabella_zoho_tasks');
const tabellaTimbrateNc = require('./tabella_timbrate_nc');
const tabellaCommesseNc = require('./tabella_commesse_nc');
const tabellaTeamsystemHrDipendenti = require('./tabella_teamsystem_hr_dipendenti');
const tabellaTeamSystemOrdiniMateriePrime = require('./tabella_teamsystem_ordini_materieprime');

module.exports = () => {
  router.use('/users', usersRoute());
  router.use('/roles', rolesRoute());
  router.use('/dashboards', dashboardsRoute());
  router.use('/kpi', kpiRoute());
  router.use('/kpi_info', kpiInfoRoute());
  router.use('/filters', filtersRoute());
  router.use('/assessments', assessmentRoute());
  router.use('/target', targetRoute());
  router.use('/emissioni', emissioniRoute());
  router.use('/limiti_inquinanti', limitiInquinanti());
  router.use('/rifiuti', rifiutiRoute());
  router.use('/materie_prime', materiePrimeRoute());
  router.use('/contatori', contatoriRoute());
  router.use('/contatori_metano', contatoriMetanoRoute());
  router.use('/punti_di_emissione', puntiDiEmissioneRoute());
  router.use('/inquinanti', inquinantiRoute());
  router.use('/tabella_gestione_impianti', tabellaImpianti());
  router.use('/tabella_gestione_impianti_ind', tabellaImpiantiInd());
  router.use('/tabella_gestione_impianti_fvf', tabellaImpiantiFvf());
  router.use('/tabella_rifiuti_prodotti', tabellaRifiuti());
  router.use('/tabella_contatori_misurazioni', tabellaContatoriMisurazioni());
  router.use('/tabella_contatori_misurazioni_metano', tabellaContatoriMisurazioniMetano());
  router.use('/tabella_manutenzione', tabellaManutenzione());
  router.use('/tabella_rit_manutenzione', tabellaRitManutenzione());
  router.use('/tabella_personale', tabellaPersonale());
  router.use('/tabella_cartellino', tabellaCartellino());
  router.use('/tabella_direzione', tabellaDirezione());
  router.use('/tabella_concorrenti', tabellaConcorrenti());
  router.use('/tabella_costo_materieprime', tabellaCostoMateriePrime());
  router.use('/tabella_budget', tabellaBudget());
  router.use('/tabella_dati_commerciali', tabellaDatiCommerciali());
  router.use('/tabella_laboratorio', tabellaLaboratorio());
  router.use('/tabella_fatturato_clienti', tabellaFatturatoClienti());
  router.use('/tabella_aumento_mp_fornitori', tabellaAumentoMpFornitori());
  router.use('/tabella_costo_fornitori', tabellaCostoFornitori());
  router.use('/tabella_riepilogo_clienti', tabellaRiepilogoClienti());
  router.use('/tabella_teamsystem_ordini', tabellaTeamsystemOrdini());
  router.use('/tabella_zoho_tasks', tabellaZohoTasks());
  router.use('/tabella_timbrate_nc', tabellaTimbrateNc());
  router.use('/tabella_commesse_nc', tabellaCommesseNc());
  router.use('/tabella_ore_formazione', tabellaOreFormazione());
  router.use('/tabella_mapping_materie_prime', tabellaMappingMp());
  router.use('/tabella_teamsystem_hr_dipendenti', tabellaTeamsystemHrDipendenti());
  router.use('/tabella_teamsystem_ordini_materieprime', tabellaTeamSystemOrdiniMateriePrime());
  router.use('/populate', populate());
  router.use('/create_widget', createWidget());
  router.use('/assign_dashboard', assignDashboard());
  return router;
};
